#!/usr/bin/env python3
#
# DECA EHCI Linux SoC — Terasic DECA with DDR3 (EMIF) + EHCI USB host.
#
# Linux-capable SoC for the Terasic DECA (MAX10 10M50):
#   - VexRiscv-SMP (linux variant, MMU, coherent DMA) @ sys_clk
#   - 512 MB DDR3 via the Intel EMIF soft controller (deca_emif.py)
#   - liteusb EHCI USB host controller on the on-board ULPI PHY
#     (CSRs @ 0xe0000000, IRQ 17, DMA master on the coherent DMA bus)
#   - UART console on the PMOD P8 GPIO header (pins 3/4, 3.3 V)
#   - SD card (SPI) for boot images + rootfs
#
# Usage
# -----
#     python3 deca_ehci_linux.py --build [--load]
#
# Boot (from the LiteX BIOS prompt):
#     spisdcardboot        # with boot.json + emulator.bin/Image/rootfs/dtb
#
# DTS (after build, generated by litex_json2dts_linux):
#     litex_json2dts_linux build/deca_ehci_linux/csr.json > rv32.dts
#     + a usb node:  usb@e0000000 { compatible="generic-ehci";
#                     reg=<0xe0000000 0x1000>; interrupts=<17>; }
#

import os

from migen import *

from litex.gen import *
from litex.build.generic_platform import Pins, Subsignal, IOStandard
from litex.soc.integration.soc import SoCRegion, SoCCore
from litex.soc.integration.builder import Builder
from litex.build.parser import LiteXArgumentParser
from litex.soc.interconnect import wishbone

from litex.soc.cores.cpu.vexriscv_smp import VexRiscvSMP

from litex_boards.platforms import terasic_deca

from liteusb.gateware.interface.ulpi import ULPIInterface
from liteusb.gateware.usb.usb2.host.ehci import USBHostController

from terasic_deca_common import DecaUSBCrg, deca_usb_sdc
from deca_emif import DecaEMIF


class DecaEHCIlinuxSoC(SoCCore):
    """DECA SoC: VexRiscv-SMP Linux + DDR3 EMIF + EHCI USB host."""

    def __init__(self, sys_clk_freq=75e6,
                 with_spi_sdcard=True,
                 sys_from_usb=False,
                 with_por=True,
                 **kwargs):

        # CPU: VexRiscv-SMP linux variant (MMU + coherent DMA bus).
        # wishbone_memory: route ALL memory accesses (I+D) through the SoC
        # wishbone bus (no direct LiteDRAM native ports — the DDR3 EMIF is a
        # plain bus slave). coherent_dma: external DMA masters (the EHCI
        # controller) enter through the cluster's coherent port, keeping the
        # L1s consistent.
        VexRiscvSMP.cpu_count       = 1
        VexRiscvSMP.wishbone_memory = True
        VexRiscvSMP.coherent_dma    = True
        kwargs.setdefault("uart_name", "serial")

        # Integrated memories (M9K budget ~204 KB total on 10M50):
        #   32 KB BIOS ROM + 32 KB main RAM + 32 KB L2 + L1 caches.
        kwargs.setdefault("integrated_rom_size", 0x10000)
        # No integrated main RAM: the DDR3 EMIF provides main_ram at
        # 0x40000000. The bridge holds CPU accesses until the EMIF has
        # completed init, so booting straight from DDR is safe.
        kwargs.setdefault("integrated_main_ram_size", 0x0)
        kwargs.setdefault("l2_size", 0x8000)

        # This target REQUIRES the VexRiscv-SMP linux variant (MMU +
        # coherent DMA). Override whatever the argument parser defaulted
        # (it passes cpu_type="vexriscv" otherwise).
        kwargs["cpu_type"]    = "vexriscv_smp"
        kwargs["cpu_variant"] = "linux"
        # Parser defaults that would otherwise defeat setdefault.
        if kwargs.get("uart_name") == "stub":
            kwargs["uart_name"] = "serial"
        if kwargs.get("integrated_rom_size") == 0x20000:
            kwargs["integrated_rom_size"] = 0x10000

        self.platform = platform = terasic_deca.Platform()

        # UART alias: "serial" -> PMOD P8 GPIO header.
        platform.add_extension([
            ("serial", 0,
                Subsignal("tx", Pins("P8:3")),
                Subsignal("rx", Pins("P8:4")),
                IOStandard("3.3-V LVTTL")),
        ])

        # ── Clocks / reset ──────────────────────────────────────────────
        # sys:   clk50 -> MAX10 PLL -> sys_clk_freq (75 MHz)
        # usb:   clk60 (ULPI PHY) -> MAX10 PLL -> 60 MHz usb domain
        #        (drives the ULPI REFCLK, same architecture as the other
        #        DECA liteusb examples)
        ulpi_plat = platform.request("ulpi", 0)
        clk60     = platform.request("clk60", 0)
        self.crg = DecaUSBCrg(platform, sys_clk_freq,
            ulpi=ulpi_plat, clk60=clk60,
            sys_from_usb=sys_from_usb, with_por=with_por)

        # ULPI I/O timing + CDC constraints.
        deca_usb_sdc(platform)

        SoCCore.__init__(self, platform, sys_clk_freq,
            ident="DECA EHCI Linux", **kwargs)

        # ── DDR3 (EMIF) = main RAM, behind a write-back L2 cache ───────
        # CPU and EHCI-DMA traffic share the same cache, so the L2 stays
        # coherent for both masters by construction.
        self.submodules.emif = emif = DecaEMIF(platform, self.crg.cd_sys)
        wb_main = wishbone.Interface(
            data_width = 32,
            adr_width  = 27,
            addressing = "word")
        self.submodules.l2 = wishbone.Cache(
            cachesize = 0x8000//4,   # 32 KB
            master    = wb_main,     # slave port on the SoC bus
            slave     = emif.bus,    # master port toward the EMIF
            reverse   = False)
        self.bus.add_slave("main_ram", wb_main,
            region=SoCRegion(origin=0x40000000, size=512*1024*1024,
                             mode="rwx", cached=True))
        self.add_constant("MAIN_RAM_SIZE", 512*1024*1024)

        # ── ULPI hookup (same adaptation as the other DECA examples) ────
        usb_ctrl = platform.request("usb", 0)
        self.comb += usb_ctrl.cs.eq(1)

        ulpi = ULPIInterface()
        self.comb += [
            ulpi.dir.eq(ulpi_plat.dir),
            ulpi.nxt.eq(ulpi_plat.nxt),
            ulpi_plat.stp.eq(ulpi.stp),
            ulpi_plat.reset_n.eq(~ulpi.rst),
        ]
        self.specials += ulpi.data.get_tristate(ulpi_plat.data)

        # ── EHCI USB Host Controller ────────────────────────────────────
        self.submodules.usb_host = host = USBHostController(
            bus=ulpi,
            handle_clocking=False,   # clocking handled by DecaUSBCrg
            num_ports=1,
        )

        # Wishbone slave: EHCI operational registers at 0xe0000000.
        self.bus.add_slave("usb_ehci", host.bus,
            region=SoCRegion(origin=0xe0000000, size=0x1000, cached=False))

        # Wishbone master: EHCI schedule structures + payload DMA in RAM,
        # on the CPU's coherent DMA bus (L2 snooping) so the CPU's caches
        # see the controller's writebacks.
        if hasattr(self, "dma_bus"):
            self.dma_bus.add_master("usb_ehci_dma", host.dma)
        else:
            raise RuntimeError("VexRiscv-SMP linux variant must provide a coherent DMA bus")

        # Interrupt routing (IRQ 17, as in the keyboard-host example).
        self.comb += self.cpu.interrupt[17].eq(host.interrupt)

        # ── SD card (SPI mode) ──────────────────────────────────────────
        if with_spi_sdcard:
            self.add_spi_sdcard()

            sd_aux = platform.request("spisdcard_aux")

            # Set the SD card supply to 3.3V
            self.comb += sd_aux.sel.eq(0)

            # Set the direction of the level shifter (0 = SD to FPGA; 1 = FPGA to SD)
            self.comb += sd_aux.cmd_dir.eq(1)
            self.comb += sd_aux.d0_dir.eq(0)
            self.comb += sd_aux.d123_dir.eq(1)

            # Keep the unused data lines high
            self.comb += sd_aux.dat1.eq(1)
            self.comb += sd_aux.dat2.eq(1)


def main():
    parser = LiteXArgumentParser(platform=terasic_deca.Platform,
        description="DECA EHCI Linux SoC (DDR3 EMIF + EHCI USB host).")
    # Keep the Linux build out of the default platform-named build dir
    # (other DECA examples use their own dirs, e.g. deca_ehci_host.py ->
    # build/deca_ehci_host).
    parser.set_defaults(output_dir="build/deca_ehci_linux")
    parser.add_target_argument("--sys-clk-freq", default=75e6, type=float,
        help="System clock frequency (default 75 MHz).")
    parser.add_target_argument("--with-spi-sdcard", action="store_true", default=True,
        help="Enable SPI SD card.")
    parser.add_target_argument("--no-spi-sdcard", action="store_false", dest="with_spi_sdcard",
        help="Disable SPI SD card.")
    parser.add_target_argument("--sys-from-usb", action="store_true",
        help="Run the sys domain from the USB 60 MHz PLL.")
    parser.add_target_argument("--no-por", action="store_true",
        help="Disable the power-on PHY reset pulse.")
    args = parser.parse_args()

    soc = DecaEHCIlinuxSoC(
        sys_clk_freq    = args.sys_clk_freq,
        with_spi_sdcard = args.with_spi_sdcard,
        sys_from_usb    = args.sys_from_usb,
        with_por        = not args.no_por,
        **parser.soc_argdict,
    )
    builder = Builder(soc, **parser.builder_argdict)
    if args.build:
        builder.build(**parser.toolchain_argdict)

    if args.load:
        prog = soc.platform.create_programmer()
        prog.load_bitstream(builder.get_bitstream_filename(mode="sram"))


if __name__ == "__main__":
    main()
